apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Get Artifact Details'
description: 'Get artifact version details.'

inputs:
  artifact-id:
    description: "The unique identifier of the artifact ID output from CloudBees platform."
    required: true

outputs:
  name:
    value: ${{ steps.getArtifactDetails.outputs.name }}
    description: 'The name of the artifact reported to CloudBees platform.'
  version:
    value: ${{ steps.getArtifactDetails.outputs.version }}
    description: 'The version of the artifact reported to CloudBees platform.'
  url:
    value: ${{ steps.getArtifactDetails.outputs.url }}
    description: 'The URL where the artifact version is located. For example, "docker.io/myapp/myimg:1.0.0".'
  digest:
    value: ${{ steps.getArtifactDetails.outputs.digest }}
    description: 'The hash or checksum that uniquely identifies the artifact version.'

runs:
  using: composite
  steps:
    - id: getArtifactDetails
      name: Get Artifact Details
      uses: docker://public.ecr.aws/l7o7z1g8/actions/cb-utils:main-0.1.59
      run: |
        
        # Print the inputs in a formatted table
        echo "+----------------------+----------------------------------------------------+"
        printf "| \033[1m%-20s\033[0m | \033[1m%-50s\033[0m |\n" "Parameter" "Value"
        echo "+----------------------+----------------------------------------------------+"
        printf "| \033[1m%-20s\033[0m | %-50s |\n" "artifact-id" "$INPUT_ARTIFACT_ID"
        echo "+----------------------+----------------------------------------------------+"
        
        # Make Platform API call to get artifact details
        response=$(curl --silent --show-error --fail-with-body \
          -X 'GET' "$URL/v3/artifactinfos/$INPUT_ARTIFACT_ID" \
          -H "Authorization: Bearer $JWT" \
          -H 'Content-Type: application/json') || command_failed=1
        
        # Check if the API call failed
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo "Platform API call failed with error: '$response'"
          exit 1
        fi
        
        # If successful, show the response nicely
        echo ""
        echo "Platform API success response:"
        echo "$response" | jq . || echo "$response"
        
        # Extract the details from the response
        aName=$(echo "$response" | grep -o '"name": *"[^"]*"' | sed 's/.*"name": *"\([^"]*\)".*/\1/')
        aVersion=$(echo "$response" | grep -o '"version": *"[^"]*"' | sed 's/.*"version": *"\([^"]*\)".*/\1/')
        aUrl=$(echo "$response" | grep -o '"url": *"[^"]*"' | sed 's/.*"url": *"\([^"]*\)".*/\1/')
        aDigest=$(echo "$response" | grep -o '"digest": *"[^"]*"' | sed 's/.*"digest": *"\([^"]*\)".*/\1/')
        
        # Set it as an output
        printf %s "$aName" > $CLOUDBEES_OUTPUTS/name
        printf %s "$aVersion" > $CLOUDBEES_OUTPUTS/version
        printf %s "$aUrl" > $CLOUDBEES_OUTPUTS/url
        printf %s "$aDigest" > $CLOUDBEES_OUTPUTS/digest
      env:
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        INPUT_ARTIFACT_ID: ${{ inputs.artifact-id }}
