= CloudBees action: Register a build artifact

Use this action to get artifact version details from the CloudBees platform.
The basic details of the artifact version like name, version, URL and digest are the outputs of this action.

== Inputs

[cols="15%a,10%a,30%a,45%a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact-id`
| String
| Yes
| The unique identifier of the artifact.

|===

[#footnote]
^[1]^ By default, the CloudBees platform associates the artifact version with the code commit associated with the workflow run in the workflow's repository/branch.
If a different commit/repository/branch has been checked out for building the artifact, specify that commit ID instead.

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===
| Output name
| Data type
| Description

| `name`
| String
| The name of the artifact reported to the CloudBees platform.

| `version`
| String
| The version of the artifact reported to the CloudBees platform.

| `url`
| String
| The URL where the artifact version is located.
For example, `docker.io/myapp/myimg:1.0.0`.

| `digest`
| String
| The hash or checksum that uniquely identifies the artifact version.


|===


== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
jobs:
  register_build_artifact:
      uses: cloudbees-io/get-artifact-details@v1
      with:
        artifact-id: "artifact-12345"
----

=== Full workflow example

The following workflow example uses the action to fetch artifact details and print them.
Then it prints the name, version, URL and digest output parameters.

.Example platform workflow YAML file
[.collapsible]
--

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  getArtifactDetailsAndPrint:
    steps:
      - name: Get Artifact Details
        id: getArtifactDetails
        uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: ea07033d-3008-40ec-9e50-a0efce7493d8
      - name: Print artifact details
        id: printArtifactDetails
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output from getArtifactDetails: "
          echo "name: ${{ steps.getArtifactDetails.outputs.name }}"
          echo "version: ${{ steps.getArtifactDetails.outputs.version }}"
          echo "url: ${{ steps.getArtifactDetails.outputs.url }}"
          echo "digest: ${{ steps.getArtifactDetails.outputs.digest }}"
----
--

== License

This code is made available under the
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
