= CloudBees action: Get artifact details

Use this action to retrieve an artifact's name, version, URL, and unique digest, using the artifact ID output from CloudBees platform.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact-id`
| String
| Yes
| The unique identifier of the artifact ID output from CloudBees platform.

|===

== Outputs

[cols="2a,1a,4a",options="header"]
.Output details
|===
| Output name
| Data type
| Description

| `name`
| String
| The name of the artifact reported to CloudBees platform.

| `version`
| String
| The version of the artifact reported to CloudBees platform.

| `url`
| String
| The URL where the artifact version is located.
For example, `docker.io/myapp/myimg:1.0.0`.

| `digest`
| String
| The hash or checksum that uniquely identifies the artifact version.


|===

== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
      - name: get-details
        uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: 1234abcd-56ef-ab78-9012-cdef78903456
----

=== Full workflow example

The following workflow example uses the action to fetch and print the details for an artifact.

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  getArtifactDetailsAndPrint:
    steps:
      - name: Get artifact details
        id: getArtifactDetails
        uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: 1234abcd-56ef-ab78-9012-cdef78903456
      - name: Print artifact details
        id: printArtifactDetails
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output from getArtifactDetails: "
          echo "name: ${{ steps.getArtifactDetails.outputs.name }}"
          echo "version: ${{ steps.getArtifactDetails.outputs.version }}"
          echo "url: ${{ steps.getArtifactDetails.outputs.url }}"
          echo "digest: ${{ steps.getArtifactDetails.outputs.digest }}"
----

== License

This code is made available under the
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[CloudBees platform].
